# This service (of type LoadBalancer) provides a single entry point for clients 
# to access multiple pods running with the label app: fastapi-app, and it allows 
# you to access those pods using port 8080.

apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-service
spec:
  # This selector is used to match this service to a Deployment or 
  # other objects that define pods.
  selector:
    app: my-fastapi
  ports:
  # Each port definition has a unique name, which can be useful 
  # for labeling and identifying purposes.
  - name: http
    port: 8080
    # The target port is used to specify the port number within 
    # the container that the traffic should be routed to.
    targetPort: 8000
  # The type of service. In this case, it's a LoadBalancer, which 
  # means the service will get its own IP address and DNS name.
  type: LoadBalancer
